config/routes.rb
Rails.application.routes.draw do
  get 'exchange_tasks', to: 'exchange_task#index'
  get 'exchange_tasks/new', to: 'exchange_task#new'
  get 'exchange_tasks/delete/:jid', to: 'exchange_task#delete', as: 'exchange_delete'
  post 'exchange_tasks', to: 'exchange_task#create'
  get 'recharge/:id', to: 'accounts#recharge', as: 'recharge'
  post 'recharge/:id', to: 'accounts#recharge_it', as: 'recharge_it'

  resources :accounts
  devise_for :users
  root 'accounts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  validates_numericality_of :amount, :greater_than_or_equal_to =>0
  validates_uniqueness_of :currency_id, scope: [:user_id]

  def currency_name
    Currency.find_by(id: self.currency_id).name
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: %i[ show edit update destroy recharge recharge_it]
  # GET /accounts or /accounts.json
  def index
    @accounts = current_user.accounts.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new 
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user = current_user
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def recharge
  end 

  def recharge_it
    new_amount = BigDecimal(params['recharge'])
    if new_amount > BigDecimal(0)
      current_amount = @account.amount
      @account.amount = current_amount + new_amount
      if @account.save
        redirect_to accounts_path
      else
        flash[:alert] = "Unexpected error!"
        render :recharge, status: :unprocessable_entity
      end
    else
      flash[:alert] = "Amount of recharge should be more than zero!"
      render :recharge, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:currency_id, :amount, :recharge)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exchange_task_controller.rb
require 'sidekiq/api'

class ExchangeTaskController < ApplicationController
  before_action :authenticate_user!

  def index
    query = Sidekiq::Queue.new 
    jobs = query.select do |job|
      job.args[0] == current_user.id
    end.map
    query_retry = Sidekiq::ScheduledSet.new
    jobs_r = query_retry.select do |job|
      job.args[0] == current_user.id
    end.map
    @jobs = jobs_r
  end

  def new
    accounts_raw = current_user.accounts
    @accounts = accounts_raw.map{|s| [Currency.find_by(id: s.currency_id).name, s.id]}
    @conditions = [[">=", 1],["=<", 2]]
  end
 
  def delete
    jid = params[:jid]
    query_retry = Sidekiq::ScheduledSet.new
    query_retry.select do |job|
      if job.args[0] == current_user.id
        job.delete if job.jid == jid
      end
    end
    redirect_to exchange_tasks_path
  end

  def create
    user_id = current_user.id
    account_id1 = params[:account_id1]
    account_id2 = params[:account_id2]
    rate_limit = params[:rate_limit]
    condition = params[:condition]
    amount = params[:amount]
    date_until = date_from_params(params, :date_until)
    if account_id1 == account_id2
      flash[:alert] = "You cann't do exchange between the same account! Please select two different accounts"
      redirect_to exchange_tasks_new_path
    elsif account_id1 != nil and account_id2 != nil and rate_limit.length > 0  and condition != nil and amount.length > 0
      ExchangeWorker.perform_async(user_id, account_id1, account_id2, amount, rate_limit, condition, date_until)
      redirect_to exchange_tasks_path
    else
      msg = ""
      if rate_limit.length == 0
        msg = msg + "Rate limit can not be blank!\n"
      end
      if condition.length == 0
        msg = msg + "Condition can not be blank!\n"
      end
      if amount.length == 0
        msg = msg + "Amount can not be blank!\n"
      end
      flash[:alert] = msg
      redirect_to exchange_tasks_new_path
    end
  end

  private

  def date_from_params(params, date_key)
    date_keys = params.keys.select { |k| k.to_s.match?(date_key.to_s) }.sort
    date_array = params.values_at(*date_keys).map(&:to_i)
    DateTime.civil(*date_array)
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_task_helper.rb
module ExchangeTaskHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :currency_id %>
    <%= form.select :currency_id, Currency.all.map{|s| [s.name, s.id]} %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Currency</th>
      <th>Amount</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.currency_name %></td>
        <td><%= account.amount %></td>
        <td><%= link_to 'Recharge', recharge_path(account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/recharge.html.erb
<%= form_with url: "/recharge/#{@account.id}", method: :post do |form| %>
  <div class="field">
    <%= form.label :recharge %>
    <%= form.text_field :recharge %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @account.user_id %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @account.currency_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @account.amount %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/exchange_task/_form.html.erb
<%= form_with url: "/exchange_tasks", method: :post do |form| %>
  <div class="field">
    <%= form.label :account_id1 %>
    <%= form.select :account_id1, accounts %>
  </div>

  <div class="field">
    <%= form.label :account_id2 %>
    <%= form.select :account_id2, accounts %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: :any %>
  </div>

  <div class="field">
    <%= form.label :rate_limit %>
    <%= form.number_field :rate_limit, step: :any %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.select :condition, conditions %>
  </div>
  <div class="field">
    <%= form.label :date_until %>
    <%= form.datetime_select(:date_until) %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exchange_task/index.html.erb
<h1>ExchangeTask#index</h1>
<table>
  <tbody>
    <% @jobs.each do |job|  %>
      <tr>
        <td><%= job.args[0] %></td>
        <td><%= job.args[1] %></td>
        <td><%= job.args[2] %></td>
        <td><%= job.args[3] %></td>
        <td><%= job.args[4] %></td>
        <td><%= job.args[5] %></td>
        <td><%= job.args[6] %></td>
        <td><%= link_to 'Delete', exchange_delete_path(job.jid) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Exchange Task', exchange_tasks_new_path %>

app/views/exchange_task/new.html.erb
<h1>New Exchange Task</h1>
<%= render 'form', accounts: @accounts, conditions: @conditions %>

<%= link_to 'Back', exchange_tasks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyTrade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= link_to 'Accounts', accounts_path %>
      <%= link_to 'Exchange Tasks', exchange_tasks_path %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>